spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: woxihuanni1314
    url: jdbc:mysql://localhost:3306/universe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false